apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: giri-oct8-2
  project: giri-may
spec:
  blueprintConfig:
    name: bp-oct8
    version: np1
  cloudCredentials: giri-aks
  config:
    kind: aksClusterConfig
    metadata:
      name: giri-oct8-2
    spec:
      managedCluster:
        apiVersion: "2024-01-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: false
            enablePrivateClusterPublicFQDN: false
          disableLocalAccounts: false
          dnsPrefix: giri-oct8-2-dns
          enablePodSecurityPolicy: false
          enableRBAC: true
          kubernetesVersion: 1.30.0
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
            networkPolicy: calico
          powerState:
            code: Running
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2024-01-01"
        name: primary
        properties:
          count: 1
          enableAutoScaling: true
          maxCount: 1
          maxPods: 110
          minCount: 1
          mode: System
          orchestratorVersion: 1.30.0
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_DS2_v2
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: giri
  type: aks
