apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: helm-workload
  project: giri-may
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/helm-workload/nginx-15.4.2.tgz
      valuesPaths:
      - name: file://artifacts/helm-workload/values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: vivek-ns
  placement:
    selector: rafay.dev/clusterName in (giri-oct3-1,giri-oct3-2)
  version: helm-workload-v1-202410040500200000
