apiVersion: apps.k8smgmt.io/v3
kind: Override
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: manifestsFile
  name: xwing-override
  project: giri-may
spec:
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-az-sep9-1
  resource:
    selector:
      name: xwing-app
    type: Workload
  sharing:
    enabled: true
    projects:
    - name: '*'
  type: Yaml
  valuesPath:
    name: file://xwing-override/xwing-override.yaml
