apiVersion: security.k8smgmt.io/v3
kind: ClusterNetworkPolicyRule
metadata:
  name: cnpr
  project: giri-may
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/cnpr/cluster-wide.yaml
    options: {}
    type: Yaml
  version: v3
