apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp-oct8
  project: giri-may
spec:
  base:
    name: default-aks
    version: 2.11.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Managed
  type: custom
  version: managed
