apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: karpenter-bp
  project: giri-may
spec:
  base:
    name: default-aks
    version: 2.11.0
  customAddons:
  - name: karpenter-addon
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  type: custom
  version: v1
