apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: metrics-disabled
  project: giri-may
spec:
  base:
    name: default
    version: 2.11.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      kubeStateMetrics:
        customizationEnabled: true
        discovery: {}
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
