apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: man
  name: man
  project: giri-may
spec:
  drift:
    action: Deny
    enabled: true
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-oct8-2
  resourceQuotas: {}
