apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  name: ns-repo
  project: giri-may
spec:
  artifact:
    path:
      name: ns-repo.yaml
    repository: giri-oct
    revision: main
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-oct8
    - key: rafay.dev/clusterName
      value: giri-oct8-2
  resourceQuotas: {}
