apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: sgfg
  description: sgfg
  name: upload-ns
  project: giri-may
spec:
  artifact:
    path:
      name: file://upload-ns/upload-ns.yaml
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-oct8
    - key: rafay.dev/clusterName
      value: giri-oct8-2
  resourceQuotas: {}
