apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: cddcd
  description: cddcd
  labels:
    env: qa
  name: wizard-ns
  project: giri-may
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-oct8
    - key: rafay.dev/clusterName
      value: giri-oct8-2
  resourceQuotas: {}
